spring.application.name=spring-security-demo

spring.security.user.name=fr3nzy
spring.security.user.password=1234

# this will make sure we can access from the same website
server.servlet.session.cookie.same-site=strict
